---
- name: create image docker
  docker_image:
    name: dadoulanda/angular:latest
    build:
      path: /var/lib/jenkins/workspace/angular
      pull: no
    source: build
    state: present
    force_source: true
- name: run docker container
  docker_container:
    name: myappcontainer
    image: dadoulanda/angular:latest
    state: started
    recreate: true
    ports:
      - "4200:80"
